### ISSUE TITLE
Feature request: pull request validation

### ISSUE THREAD

**Issue by michailw** [aeon-php/automation#12]
I would like to request a command which checks if a merge request is valid with the changelog template. Otherwise, it should exit with a non-zero exit code. That would be useful for any pull request pipeline to automatically check if a developer didn't make any mistakes.

**Comment by norberttech** [comment]
lol you are reading my mind, I was going to work on this tomorrow and make it part of the default workflow for all aeon projects since they all follow the same strategy. I was just waiting for the docker image since it simplifies integration with github actions. 

https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#issues I think it could be potentially triggered when the issue is opened or updated (only pr). 
Additionally, I wanted to check not only if the PR descriptions match the pattern but also how many changes are detected, if less than 1 also returns non-zero status which will fail the workflow/pipeline. 

Technically speaking it should also not be very hard to take all commits from the pull request scope, parse them, and append the changelog into the pull request description automatically.

**Comment by norberttech** [comment]
it was easier than I thought, @michailw could you please confirm that #13 is what you have been thinking about?

**Comment by michailw** [comment]
It's perfect, thank you.
